- src/App.tsx
- src/components/Footer/footer.module.css
- src/components/PostCard/postCard.module.css
- src/components/PostCard/postCard.tsx
- src/pages/RoomMate/roomMate.module.css
- src/pages/RoomMate/roomMate.tsx
* 룸메이트 페이지 제작
* 포스트 카드 제작
* 푸터 css 변경 (position 삭제, bottom 삭제)
> add : 룸메이트 페이지 제작, 포스트 카드 제작, 푸터 css 변경

- package-lock.json
- package.json
- src/components/MainPostCard/mainPostCard.tsx
- src/components/MainPostCard/mainpostCard.module.css
- src/components/RecommendCard/recommendCard.module.css
- src/components/RecommendCard/recommendCard.tsx
- src/pages/MainPage/mainPage.module.css
- src/pages/MainPage/mainPage.tsx
* 메인페이지 html css 구현
* 멀티 캐러셀 및 리액트 캐러셀 설치
* mainpagecard, recommendcard 제작
> Main page add

- src/Redux/user.ts
- src/components/PostCard/postCard.module.css
- src/components/PostCard/postCard.tsx
- src/interface/interface.ts
- src/pages/RoomMate/roomMate.tsx
- src/pages/SignUp/signUp.tsx
* API 패치
* interface 수정
* 룸메이트 페이지 수정
> add : API 패치, interface 수정, 룸메이트 페이지 수정

- src/App.tsx
- src/assets/posts.json
- src/pages/MyPage/Applicant/applicant.tsx
- src/pages/MyPage/Board/board.tsx
- src/pages/MyPage/Favorites/favorite.tsx
- src/pages/MyPage/Proflie/profile.tsx
- src/pages/MyPage/myPage.tsx
* mypage 탭 부분 수정 
* json파일 recruit --> isRecruit 수정
> edit : mypage 탭 부분 수정

- src/Redux/localStorage.ts
- src/Redux/store.ts
- src/Redux/user.ts
- src/assets/posts.json
- src/components/Header/Alarm/alarm.module.css
- src/components/Header/header.module.css
- src/components/Header/header.tsx
- src/components/PostCard/postCard.tsx
- src/interface/interface.ts
- src/pages/Login/login.tsx
- src/pages/RoomMate/roomMate.module.css
- src/pages/RoomMate/roomMate.tsx
- src/pages/RoomMate/roomMateSearch.module.css
- src/pages/RoomMate/roomMateSearch.tsx
- src/pages/SignUp/signUp.tsx
* Logo import
* 룸메이트 검색창 구현 마무리 (검색창 사이즈 변경, onChange추가, css 수정)
* 로그인, 회원가입 API 연동
* 로그인 시 헤더 변경 (로그인, 로그아웃, 마이페이지)
> add : 로그인 회원가입 연동 완료, interface추가, 페이지네이션 수정, 헤더 수정

- src/Redux/localStorage.ts
- src/Redux/store.ts
- src/interface/interface.ts
- src/pages/RoomMate/roomMateSearch.module.css
- src/pages/RoomMate/roomMateSearch.tsx
* 로그인 상태 유지(로컬스토리지)
* store 상태 유지 추가
* interface 추가
> add : 로컬스토리지 수정, store 수정, search 수정, interface 수정

- package-lock.json
- package.json
- src/App.tsx
- src/components/PostModal/postModal.module.css
- src/components/PostModal/postModal.tsx
- src/pages/RoomMate/roomMate.tsx
- src/pages/WritePage/writePage.tsx
**AS-IS**
add : 글쓰기페이지 제작
**TO-BE**
> add : 글쓰기 페이지 제작

- src/components/PostCard/postCard.tsx
- src/pages/Login/login.tsx
- src/pages/RoomMate/roomMate.tsx
- 룸메이트 구하기 페이지 로그인한 사용자만 포스트 카드 모달이 열리도록 수정
> add : 룸메이트 구해요 페이지 수정

- src/Redux/user.ts
- src/pages/WritePage/writePage.module.css
- src/pages/WritePage/writePage.tsx
- src/pages/WritePage/writePageSelect.module.css
- src/pages/WritePage/writePageSelect.tsx
> Write page connect

- .env
- package.json
> add : env, package.json 수정

- .env
- .gitignore
- src/Redux/localStorage.ts
- src/Redux/user.ts
- src/components/Footer/footer.tsx
- src/components/PostCard/postCard.tsx
- src/object/profileDropdown.ts
- src/pages/Login/login.tsx
- src/pages/RoomMate/roomMate.tsx
- src/pages/RoomMate/roomMateSearch.module.css
- src/pages/RoomMate/roomMateSearch.tsx
- env 삭제
- 룸메이트 페이지 검색창 부분 수정
- 로그인 모달 2번 뜨는 오류 수정
> add : env 삭제, 룸메이트 페이지 검색창 수정, 로그인 모달 오류 수정

- src/pages/RoomMate/roomMateSearch.tsx
- 검색하기 버튼 수정 (라디오 버튼 선택 후 검색하기 버튼을 누르면 모달 닫힘)
> add : 룸메이트 검색창 버튼 수정

- src/pages/WritePage/writePageSelect.tsx
> edit : writePageSelect 수정

- src/Redux/localStorage.ts
- src/Redux/user.ts
- src/components/Header/header.tsx
- src/interface/interface.ts
- src/pages/Login/login.tsx
> add : login token 수정

- src/components/PostCard/postCard.tsx
- src/pages/RoomMate/roomMateSearch.tsx
> add : userArticleRecent 수정

- src/components/PostCard/postCard.tsx
> edit : postCard fetch 부분 수정

- src/api.ts
- src/components/PostCard/postCard.tsx
- src/interface/interface.ts
> edit: postCard 수정

- src/components/PostCard/postCard.tsx
> edit: postCard filter 변경

- src/App.tsx
- src/components/MainPostCard/mainPostCard.tsx
- src/components/MainPostCard/mainpostCard.module.css
- src/components/PostModal/postModal.tsx
- src/pages/EditPage/editPage.module.css
- src/pages/EditPage/editPage.tsx
- src/pages/EditPage/editPageSelect.module.css
- src/pages/EditPage/editPageSelect.tsx
- src/pages/MainPage/mainPage.tsx
edit : mainPage 및 mainPostCard css 수정
- editPage 추가
- mainPage, mainPostCard css 수정
> add : editPage추가

- src/Redux/user.ts
- src/components/PostCard/postCard.tsx
- src/interface/interface.ts
- src/pages/Login/login.tsx
- 로컬스토리지 email 저장
로컬스토리지 email 저장되는 부분을 급하게 필요로 하셔서 간단히 구현한 상태라 이 후 수정이 있을 예정 입니다.
> edit : 로컬스토리지에 email 저장

- src/App.tsx
- src/components/PostModal/postModal.tsx
- src/pages/EditPage/editPage.tsx
- src/pages/EditPage/editPageSelect.tsx
- src/pages/MainPage/mainPage.tsx
- editPage 수정
- postModal 수정, 삭제버튼 구현
> edit : edtiPage 수정, postModal 수정 삭제 버튼 구현

- package-lock.json
- package.json
- src/Redux/user.ts
- src/components/PostCard/postCard.module.css
- src/components/PostCard/postCard.tsx
- src/interface/interface.ts
> edit : 룸메이트 구해요 페이지 카드 수정

- src/components/PostModal/postModal.tsx
- postModal.tsx 찜하기 코드 추가 (API 연동 테스트 코드)
> add : postModal 찜하기 기능 구현

- src/components/Header/Alarm/alarm.module.css
- src/components/Header/Alarm/alarm.tsx
- src/pages/WritePage/writePageSelect.module.css
- 알림창 수정 : 알림창 프로필 클릭 시 모달이 보이도록 수정
- 프로필 모달 : readOnly (check box 부분은 readOnly 옵션이 없어 추가 로직 작성)
- writePageSelect CSS : 가로 스크롤 안 보이도록 수정
> edit : 알림창 수정, 글쓰기 페이지 CSS 수정

- src/Redux/user.ts
- src/pages/Login/login.tsx
- 로그인 버튼을 클릭 시 메인페이지로 이동이 되지 않는 버그 수정
> HotFix : 로그인 페이지 보완

- src/Redux/user.ts
- src/api.ts
> add: 공통함수 폴더 생성, edit: 자동 로그인

- src/Redux/user.ts
- src/api.ts
- src/pages/RoomMate/roomMateSearch.tsx
> edit: 룸메이트 필터링 API 연동

- src/Redux/user.ts
- src/interface/interface.ts
- src/pages/SignUp/signUp.tsx
- 회원가입 시 로그인 페이지로 넘어가지 않는 오류 수정
> HotFix: 회원가입 시 로그인 페이지로 넘어가지 않는 오류 수정

- src/components/PostCard/postCard.tsx
- src/main.tsx
- src/pages/RoomMate/roomMate.tsx
- main.tsx 수정 (strict 삭제)
- 페이지네이션 수정 (전체 게시글 개수 API 연동)
> edit : 룸메이트 구해요 페이지 수정, main.tsx 수정

- src/components/MainPostCard/mainpostCard.module.css
- src/components/PostModal/postModal.module.css
- src/components/PostModal/postModal.tsx
- src/components/RecommendModal/recommendModal.tsx
- src/pages/MainPage/mainPage.module.css
- src/pages/MainPage/mainPage.tsx
- postModal 삭제 구현 및 css 수정
- MainPage 캐러셀 문제 해결
- visual 에러 해결
- mainPostCard css 수정
> edit : postModal 삭제 구현, MainPage 광고 캐러셀 수정, visual에러 수정

- src/components/PostModal/postModal.tsx
- src/main.tsx
- src/pages/MyPage/Favorites/favorite.tsx
> add : 찜하기 useCallBack 추가

- package-lock.json
- package.json
- src/interface/interface.ts
- src/pages/MyPage/Proflie/profile.module.css
- src/pages/MyPage/Proflie/profile.tsx
- src/pages/MyPage/Proflie/profileBasic.tsx
- src/pages/MyPage/Proflie/profileTendency.tsx
- vite.config.ts
* add : 마이페이지 프로필 GET 연동 및 데이터 수정, 화면 수정
> add : 마이페이지 프로필 GET 데이터 수정

- src/Redux/user.ts
> eidt : 카카오 로그인 수정

- src/api.ts
- src/pages/Login/login.tsx
- src/pages/RoomMate/roomMate.tsx
- 룸메이트 구해요 페이지 새로고침 버튼 생성, 버튼 디자인 변경
- api.ts 변경
> edit : 룸메이트 구해요 페이지 새로고침 버튼 생성, api.ts 변경

- src/Redux/user.ts
- src/api.ts
* proxy 주소 설정에 맞게 api.ts 수정 
* API 연동 주소 수정
> edit : proxy 주소 설정에 맞게 api.ts 수정 및 API 연동 주소 수정

- src/App.tsx
- src/Redux/localStorage.ts
- src/Redux/user.ts
- src/api.ts
- src/components/Kakao/kakao.tsx
- src/components/PostCard/postCard.tsx
- src/interface/interface.ts
- src/pages/Login/login.tsx
- src/pages/RoomMate/roomMate.tsx
- vite.config.ts
- 카카오 소셜 로그인 인가 코드 넘기기
- 룸메이트 구해요 페이지 수정 - 모집글, 전체글 토글
> edit : 카카오 로그인 수정, 룸메이트 구해요 페이지 수정 add : kakao.tsx

- src/components/Footer/footer.module.css
- src/components/PostCard/postCard.tsx
- src/pages/RoomMate/roomMate.module.css
- src/pages/RoomMate/roomMate.tsx
- 룸메이트 구해요 페이지 CSS 수정, 모집 & 마감 뱃지 컬러 변경 및 isRecruiting -> recruiting 변경
> edit : 룸메이트 구해요 페이지 수정

- src/components/Header/header.module.css
- src/components/Header/header.tsx
- Header CSS 수정 - nav hover 시 transition 추가, logo hover transition 추가
> edit : Header CSS 수정

- src/components/Header/Alarm/alarm.module.css
- src/components/Header/Alarm/alarm.tsx
- src/components/Header/header.module.css
- src/components/Header/header.tsx
> edit : 헤더 디자인 변경

- src/components/Header/Alarm/alarm.module.css
- src/components/Header/Alarm/alarm.tsx
- src/components/Header/header.module.css
- src/components/Header/header.tsx
- src/pages/MainPage/mainPage.tsx
- src/pages/WritePage/writePage.tsx
- 헤더 드롭다운 수정
- fetch 수정 /api/ 추가
> edit : 헤더 수정, 메인&글쓰기 fetch 수정

- src/components/Chat/chat.module.css
- src/hooks/useFetch.ts
- useFetch 커스텀 훅 제작
- chat css 수정
> add : useFetch 커스텀 훅 제작

- src/Redux/user.ts
- src/api.ts
- src/components/Header/header.tsx
- src/components/Kakao/kakao.tsx
- src/interface/interface.ts
- src/pages/Login/login.tsx
> edit : 로컬스토리지 값 수정

- src/components/MbtiCalculator/mbitCalculator.tsx
- src/pages/MainPage/mainPage.module.css
- src/pages/MainPage/mainPage.tsx
> edit : css

- src/interface/interface.ts
- src/pages/MyPage/Applicant/applicant.tsx
- src/pages/MyPage/Applicant/apply.tsx
* 프로필 신청현황
- Apply 파일과 Apply type 중복 수정
> edit : Apply 파일과 Apply type 중복 수정

- src/components/PostModal/postModal.tsx
- src/interface/interface.ts
- src/pages/MainPage/mainPage.tsx
- src/pages/RoomMate/roomMate.tsx
> edit : interface any 수정

- src/interface/interface.ts
- src/pages/RoomMate/roomMate.tsx
> edit : 검색 필터링 구현

- src/components/PostCard/postCard.tsx
- src/pages/RoomMate/roomMate.tsx
- 검색창 모달 검색 후 모달이 닫히지 않는 오류 수정
> HotFix : 검색창이 닫히지 않는 오류 수정

- src/components/BoardCard/boardCard.tsx
- src/components/Header/Alarm/alarm.tsx
- src/components/MainPostCard/mainPostCard.tsx
- src/components/RecommendModal/recommendModal.tsx
- src/interface/interface.ts
- src/pages/RoomMate/roomMate.tsx
- src/pages/WritePage/writePage.tsx
> HotFix : any type 변경

- src/interface/interface.ts
> edit : 인터페이스 정리

- src/components/Favorite/SaveButton.tsx
- src/components/PostModal/postModal.tsx
- src/interface/interface.ts
- src/pages/MyPage/Favorites/favorite.tsx
add : 찜하기 기능 컴포넌트 구분 시도
edit : 마이페이지 찜한 목록 가져오기 상위 컴포넌트 구분
add : 찜하기 기능 컴포넌트 구분 시도
> edit : 찜한 목록 가져오기 상위컴포넌트 구분

- src/components/Footer/footer.module.css
- src/components/Footer/footer.tsx
> Edit : 푸터 CSS 수정

- src/components/SearchBar/searchBar.tsx
- src/pages/RoomMate/roomMate.module.css
- 검색하기 버튼 클릭 시 모달이 닫히지 않는 버그 수정
> HotFix : 검색하기 버튼 클릭 시 모달이 닫히지 않는 버그 수정

- src/components/SearchBar/searchBar.module.css
- src/object/profileDropdown.ts
> Edit : 검색 필터링 추가 (상관 없음)

- src/api.ts
- src/components/PostModal/postModal.tsx
- src/components/RecommendCard/recommendCard.module.css
- src/components/RecommendCard/recommendCard.tsx
- src/interface/interface.ts
- src/pages/EditPage/editPage.tsx
- src/pages/MainPage/mainPage.tsx
> edit : 추천카드 구현

- src/hooks/useFetch.ts
> edit : useFetch 수정

- src/components/SearchBar/searchBar.tsx
- src/object/profileDropdown.ts
- src/pages/RoomMate/roomMate.tsx
> edit : profileDropdown 수정

- src/Redux/user.ts
- 카카오 로그인 시 저장이 되도록 했습니다.
아직 서버 측에서 카카오 Email을 전달하는 부분이 구현 됐는지는 확인 되지 않았습니다.
> edit : 카카오 로그인 시 이메일 저장

- src/App.tsx
- src/Redux/user.ts
- src/api.ts
- src/components/SocialLogin/google.tsx
- src/components/SocialLogin/kakao.tsx
- src/interface/interface.ts
- src/pages/Login/login.tsx
> edit: 구글 로그인 수정, add: google.tsx 생성

- src/pages/RoomMate/roomMate.tsx
> edit : roommate 페이지 수정

- src/pages/MyPage/Board/board.module.css
- src/pages/MyPage/Favorites/favorite.module.css
- src/pages/MyPage/Proflie/profile.tsx
- src/pages/MyPage/Proflie/profileBasic.tsx
- src/pages/MyPage/Proflie/profileFile.tsx
- src/pages/MyPage/Proflie/profileTendency.tsx
edit : API 연동 관련 console.log() 삭제
* edit : 마이페이지 작성한글, 찜한 목록 css 수정
* edit : API 연동 관련 console.log() 삭제
> 마이페이지 css 및 API 콘솔 삭제

- src/pages/MyPage/Proflie/profileFile.tsx
add : 이미지 크기 10MB 제한 추가
add : 파일 jpeg, png만 업로드 가능
* 프로필 파일 업로드 시
: 이미지 크기 10MB 제한
: 파일 jpeg, png만 업로드 가능
> 프로필 파일 업로드 시

- src/components/SocialLogin/google.tsx
- src/pages/Login/login.tsx
> edit : 구글 로그인 Access 오류 수정

- src/Redux/user.ts
- src/api.ts
- src/pages/SignUp/signUp.tsx
- 회원가입 시 로컬스토리지 isLogged 부분 수정
> HotFix : 회원가입 시 isLogged 수정

- src/Redux/user.ts
- src/components/SocialLogin/google.tsx
- 토큰이 제대로 넘어가지 않는 부분 수정 후 연동 완료
> edit : 구글 로그인 수정

- src/interface/interface.ts
- src/pages/MyPage/Applicant/applicant.tsx
- src/pages/MyPage/Applicant/apply.tsx
- src/pages/MyPage/Proflie/profile.tsx
edit : 신청현황 컴포넌트 수정
* edit : 프로필 '연령대' 데이터 수정
* edit : 신청현황 컴포넌트 수정
> edit : 프로필 '연령대' 데이터 수정

- src/pages/RoomMate/roomMate.tsx
> HotFix: Response 변경 수정

- src/hooks/useFetch.ts
- src/pages/MainPage/mainPage.tsx
- src/pages/RoomMate/roomMate.tsx
> edit : useFetch

- src/Redux/user.ts
- src/components/PostCard/postCard.tsx
> edit : 소셜 로그인 email 삭제 추가

- src/components/PostModal/postModal.tsx
- src/components/RecommendCard/recommendCard.tsx
- src/components/RecommendModal/recommendModal.tsx
- src/interface/interface.ts
- src/pages/EditPage/editPage.tsx
- src/pages/MainPage/mainPage.tsx
- src/pages/WritePage/writePage.tsx
> edit : useFetch 사용

- src/components/PostModal/postModal.tsx
- src/components/RecommendModal/recommendModal.module.css
- src/components/RecommendModal/recommendModal.tsx
- src/pages/MainPage/mainPage.tsx
> edit : 게시글 CSS 수정

- src/components/PostModal/postModal.tsx
- src/pages/MyPage/Applicant/applicant.module.css
- src/pages/MyPage/Applicant/applicant.tsx
- src/pages/MyPage/Applicant/apply.tsx
> edit : 신청현황 백엔드 연동

- src/Redux/user.ts
> edit : 자동 로그아웃 추가

- src/components/RecommendModal/recommendModal.module.css
- src/components/RecommendModal/recommendModal.tsx
> edit : 추천 프로필 모달 CSS 변경

- src/components/RecommendModal/recommendModal.tsx
- src/interface/interface.ts
- src/pages/MyPage/Applicant/applicant.tsx
* add : 신청현황 상대 user 프로필 api 연동
(recommendModal.tsx 구조 수정)
* edit : 추천 프로필 흡연 데이터 수정 (issmoke -> isSmoker)
> add : 신청현황 상대 user 프로필 api 연동 (으로 recommendModal.tsx 구조 수정)

- src/components/PostModal/postModal.tsx
- src/components/RecommendCard/recommendCard.tsx
- src/interface/interface.ts
- src/pages/MainPage/mainPage.module.css
- src/pages/MainPage/mainPage.tsx
-recommendtitle 내정보 입력 안하면 제목 바뀜
> edit : recommend 제목 수정

- src/pages/MyPage/Applicant/applicant.tsx
> add : 신청현황 게시물 보여주기 추가

- src/pages/MyPage/Applicant/applicant.tsx
- src/pages/MyPage/Applicant/otherUserProfile.tsx
* edit : recommendModal.tsx에서 신청현황 부분 사용하지 않기로 결정 -> 원상복구
* add : 신청현황 프로필 부분 새로 컴포넌트 구현하여 수정 및 otherUserProfile.tsx 추가
> 신청현황 (프로필, 게시글) 구조 수정 및 추가

- src/Redux/applicantReducer.ts
- src/Redux/applyAction.ts
- src/Redux/applyReducer.ts
- src/Redux/store.ts
- src/components/Apply/applyApi.ts
- src/components/PostModal/postModal.tsx
- src/pages/MyPage/Applicant/applicant.tsx
- src/pages/MyPage/Applicant/apply.tsx
> add : 신청현황 redux로 전역관리

- src/Redux/applyReducer.ts
- src/Redux/applySavedReducer.ts
- src/Redux/store.ts
- src/components/Apply/applyApi.ts
- src/components/PostModal/postModal.tsx
* edit : 신청하기, 신청 취소하기 redux 실시간 업데이트 구현
* applySavedReducer 파일 추가
> 신청하기, 신청 취소하기 redux 실시간 업데이트 구현

- src/components/Apply/applyApi.ts
* add : 거절 이력이 있거나 마감 게시글인 경우, Modal창 띄우기
> 거절 이력이 있거나 마감 게시글인 경우, Modal창 띄우기

- package-lock.json
- package.json
- src/components/Header/chat/chat.tsx
- vite.config.ts
* add : @stomp/stompjs, sockJS 설치
* add : sockJS 오류 해결을 위한 vite.config.ts 추가
* add : 채팅 서버 구현 일부 추가
>  @stomp/stompjs, sockJS 설치

- src/Redux/user.ts
- src/components/Header/chat/chat.tsx
- src/interface/interface.ts
* add : 채팅 기능 구현 추가
* edit : 구글 로그인 오류 해결
> 채팅 기능 구현 추가

- package-lock.json
- package.json
- src/components/Header/chat/chat.module.css
- src/components/Header/chat/chat.tsx
* edit : 채팅 리스트 없을 경우, 화면 표시
* edit : 채팅 스크롤, 입력 두 줄 수정
* add : moment를 통한 화면 표시
> 채팅 컴포넌트 수정

- src/interface/interface.ts
- src/pages/EditPage/editPage.tsx
> edit : any 타입 변경

- src/Redux/user.ts
- src/interface/interface.ts
> 카카오 소셜로그인 이메일 전달 수정

- src/components/PostModal/postModal.module.css
- src/pages/MainPage/mainPage.tsx
- 내정보를 입력하지 않고 메인페이지를 가면 내정보를 입력해달라고 모달창이 나옴
> edit : 회원가입 후 내 정보를 입력하도록 수정

- index.html
- src/Redux/applyReducer.ts
- src/Redux/user.ts
- src/components/Apply/applyApi.ts
- src/components/Favorite/useFavorite.ts
- src/components/Header/chat/chat.tsx
- src/pages/EditPage/editPage.module.css
- src/pages/EditPage/editPage.tsx
- src/pages/EditPage/editPageSelect.tsx
- src/pages/MyPage/Applicant/applicant.tsx
- src/pages/MyPage/Proflie/profile.tsx
- src/pages/WritePage/writePage.module.css
- src/pages/WritePage/writePage.tsx
- src/pages/WritePage/writePageSelect.tsx
- vite.config.ts
> Consolelog

- src/components/Header/chat/chat.module.css
- src/components/PostModal/postModal.module.css
- src/pages/MainPage/mainPage.module.css
- src/pages/MyPage/Applicant/applicant.tsx
- src/pages/RoomMate/roomMate.module.css
-add : 신청현황 채팅방 만들기 useFetch 사용
-edit : 전체적인 css 수정
> 신청현황 채팅방 만들기 useFetch 사용

- src/Redux/applicantReducer.ts
- src/components/Apply/applyApi.ts
- src/components/Header/chat/chat.tsx
- src/pages/MyPage/Board/board.tsx
- src/pages/MyPage/Proflie/profileBasic.tsx
- src/pages/MyPage/Proflie/profileFile.tsx
- src/pages/MyPage/Proflie/profileTendency.tsx
- src/pages/WritePage/writePage.tsx
- vercel.json
-edit : 컴포넌트 및 줄바꿈, css 등 전체적인 수정
> 컴포넌트 및 줄바꿈, css 등 전체적인 수정

- vercel.json
>  vercel.json 수정

- vercel.json
> vercel.json 수정

- src/Redux/user.ts
- src/components/Header/chat/chat.module.css
- src/components/Header/chat/chat.tsx
- src/components/RecommendModal/recommendModal.tsx
- src/interface/interface.ts
- src/pages/MainPage/mainPage.tsx
- src/pages/MyPage/Applicant/applicant.tsx
- src/pages/RoomMate/roomMate.tsx
- src/pages/SignUp/signUp.tsx
- vercel.json
* css 수정, error 변경, ngrok 삭제, 회원가입 수정
> Refactoring all

- index.html
- src/Redux/user.ts
- src/components/Header/chat/chat.tsx
- src/pages/SignUp/signUp.tsx
- add : 회원가입 이메일, 닉네임 중복 검사 추가
- edit : refactoring
> 회원가입 이메일, 닉네임 중복 검사 추가

- index.html
- src/components/PostModal/postModal.module.css
- src/interface/interface.ts
- src/pages/EditPage/editPage.tsx
- src/pages/MainPage/mainPage.tsx
- src/pages/RoomMate/roomMate.tsx
- src/pages/WritePage/writePage.tsx
- vercel.json
> Search edit

- src/pages/MainPage/mainPage.tsx
> edit : 무한루프

- src/components/RecommendModal/recommendModal.tsx
- src/pages/MainPage/mainPage.tsx
> edit : 게시물 2번쨰 요청 오류 수정

- README.md
> Hwang ji minn patch 4
